remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

locale: "zh-CN"
title: "标题"
subtitle: "子标题"
name: "网站name"
description: "网站描述"
logo: "/assets/img/code.png"